version: 2

jobs:
  build:
    environment:
      IMAGE_NAME: thehubaubg/unimorph-frontend
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker build -t $IMAGE_NAME:latest .
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker push $IMAGE_NAME:latest

workflows:
      version: 2
      deploy:
        jobs:
          - build:
              filters:
                branches:
                  only:
                    - master