name: Docker Image Build

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: thehubaubg/unimorph-frontend
        tags: latest

    - name: SSH Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: docker-compose -f deploy/production.yml down && docker-compose -f deploy/production.yml pull && docker-compose -f deploy/production.yml up -d
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.PRIVATE_KEY }}